#!/usr/bin/env python

import sys
import tabulate
from cloudfoundry import CloudFoundry

if __name__ == '__main__':
    cf = CloudFoundry()
    apps = cf.apps()    
    print tabulate.tabulate(apps, headers='firstrow')
